image: alpine

before_script: 
  - apk update 
  - apk add openssh sshpass lftp

deploy_pages: 
  stage: deploy 
  script: 
    - ls -al 
    - echo "pwd" | sshpass -p $FTP_PASSWORD sftp -o StrictHostKeyChecking=no bitrix@91.232.135.86 
    - lftp -e "mirror --delete -R /public/ /home/bitrix/www/bitrix24/pet-todo" -u bitrix,$FTP_PASSWORD sftp://91.232.135.86 